# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99b1c94f30e26f7e4302d680f0d664eadfcaf327fdd39a7ecddab5e0fde834701cd7fe0af55259b6c695811269c66da73188b43c4fb8a3b304a114f7c5cc3760

test:
  secret_key_base: d8dcbccb7855322b295fd2d4d8a4b69fd52f5f432bfe6fff366fae31e1dde2655fa26badc09c8f44364adc7de6d7ad948c3a6ad4a592af0097bd01d572c93add

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
